services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dartfrog_backend
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cards-database:
    image: cards-database
    build:
      context: backend
      dockerfile: ./deps/cards-database/Dockerfile
    restart: always
    ports:
      - "3000:3000"