services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: your_username
  #     POSTGRES_PASSWORD: your_password
  #     POSTGRES_DB: your_database_name
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  cards-database:
    image: cards-database
    build:
      context: backend
      dockerfile: ./deps/cards-database/Dockerfile
    restart: always
    ports:
      - "3000:3000"